dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f libwlupnp.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libwlupnp.so
	cp -f eapd_AR-5315u_PLD_save $(INSTALL_DIR)/bin/eapd
	cp -f lld2d_AR-5315u_PLD_save $(INSTALL_DIR)/bin/lld2d
	cp -f wrt54g.large.ico_AR-5315u_PLD_save $(INSTALL_DIR)/etc/wrt54g.large.ico
	cp -f wrt54g.small.ico_AR-5315u_PLD_save $(INSTALL_DIR)/etc/wrt54g.small.ico
	cp -f nas_AR-5315u_PLD_save $(INSTALL_DIR)/bin/nas
	cp -f nvram_AR-5315u_PLD_save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_AR-5315u_PLD_save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_AR-5315u_PLD_save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlctl_AR-5315u_PLD_save $(INSTALL_DIR)/bin/wlctl
	cp -f libwlctl.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libwlctl.so
	cp -f wlmngr_AR-5315u_PLD_save $(INSTALL_DIR)/bin/wlmngr
	cp -f wlevt_AR-5315u_PLD_save $(INSTALL_DIR)/bin/wlevt
	cp -f libwlmngr.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f wps_monitor_AR-5315u_PLD_save $(INSTALL_DIR)/bin/wps_monitor
	cp -f libwps.so_AR-5315u_PLD_save $(INSTALL_DIR)/lib/libwps.so
